name: w_quake
description: ""
publish_to: 'none'
version: 1.1.0+03

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  go_router: ^16.3.0
  flutter_riverpod: ^3.0.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app_logo.png

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_logo.png
  adaptive_icon_foreground: assets/images/app_logo.png
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  min_sdk_android: 21

# Splash screen configuration
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: assets/images/app_logo.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#000000"
    image: assets/images/app_logo.png
    icon_background_color: "#000000"
